# Generated by Django 3.2.8 on 2022-12-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('na', models.CharField(max_length=20)),
                ('ad', models.CharField(max_length=20)),
                ('ge', models.CharField(max_length=20)),
                ('ph', models.CharField(max_length=20)),
                ('do', models.CharField(max_length=20)),
                ('co', models.CharField(max_length=20)),
                ('im', models.FileField(upload_to='')),
                ('us', models.CharField(max_length=20)),
                ('pa', models.CharField(max_length=20)),
            ],
        ),
    ]
