# Generated by Django 3.2.8 on 2022-12-30 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_register_tb_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register_tb',
            new_name='seller_register_tb',
        ),
    ]
