# Generated by Django 3.2.8 on 2023-01-03 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0002_category_tb'),
        ('seller', '0003_rename_register_tb_seller_register_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('image', models.FileField(upload_to='')),
                ('stock', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.category_tb')),
                ('sellerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller_register_tb')),
            ],
        ),
    ]
